
name: Standards Collab Space 
on:
  workflow_dispatch: 

jobs:
  create_issue:
    name: Create agenda issue
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create agenda issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          meeting_date=`date +"%Y-%m-%d" -d "next Tuesday"`
          new_issue_url=$(gh issue create \
            --title "$meeting_date OpenJS Foundation Collaboration Space Meeting" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ASSIGNEES: jorydotcom
          LABELS: standards-agenda
          BODY: |
            ## Meeting notices

            **Reminder - Meeting is recorded**

            ## Agenda
             - [ ] OpenJS Announcements, Reminders & FYIs
             - [ ] Liaison Reports
             - [ ] Review Open Issues and PRs
             - [ ] Any Other Business

            ### OpenJS Announcements, Reminders & FYIs
              - [ ] Add any project shares, news, FYIs or reminders to share with the community
              
            ### Liaison Reports 
              - [ ] TC 39 
              - [ ] TC 53
              - [ ] W3C AC
              - [ ] W3C TAG
              - [ ] OSI
              - [ ] OPA

            ## [Review Open Issues & PRs](https://github.com/openjs-foundation/standards/labels/standards-agenda) 
              - [ ] Add issues that need review, assignment, triage, or other clarification

            ## AOB
              - [ ] Add any other items

            ## Adjournment
          PINNED: false
          CLOSE_PREVIOUS: false
